-- georgia
-- Author: Cezas
-- DateCreated: 9/4/2021 4:04:06 PM
--------------------------------------------------------------
UPDATE Units SET Cost=180, Combat=45, PrereqTech='TECH_CASTLES' WHERE UnitType='UNIT_GEORGIAN_KHEVSURETI'; 
INSERT INTO Building_BuildChargeProductions (BuildingType, UnitType, PercentProductionPerCharge) VALUES 
	('BUILDING_TSIKHE','UNIT_MILITARY_ENGINEER', 10)
	;

--PLAYER_HAS_GOLDEN_AGE
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES 
	('SIXFIX_TAMAR_FAITH_PURCHASE_DISCOUNT_IN_GOLDEN_AGE', 'MODIFIER_PLAYER_GOVERNMENT_FLAT_BONUS', 'PLAYER_HAS_GOLDEN_AGE')

	--('SIXFIX_TAMAR_MORE_FAITH_ON_KILL_IN_GOLDEN_AGE', 'MODIFIER_PLAYER_UNITS_ADJUST_POST_COMBAT_YIELD', 'PLAYER_HAS_GOLDEN_AGE'),

	--this should really be a georgian ability rather than tamar's ability
	--('SIXFIX_TAMAR_EXTRA_COMBAT_STRENGTH_IN_GOLDEN_AGE', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 'PLAYER_HAS_GOLDEN_AGE'),
	--('SIXFIX_TRAIT_COMBAT_BONUS_WHEN_IN_GOLDEN_AGE', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', NULL)
	;
/*
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('SIXFIX_TAMAR_FAITH_PURCHASE_DISCOUNT_IN_GOLDEN_AGE', 'BonusType', 'GOVERNMENTBONUS_FAITH_PURCHASES'),
	('SIXFIX_TAMAR_FAITH_PURCHASE_DISCOUNT_IN_GOLDEN_AGE', 'Amount', 50),
	
	('SIXFIX_TAMAR_MORE_FAITH_ON_KILL_IN_GOLDEN_AGE', 'PercentDefeatedStrength', 50),
	
	('SIXFIX_TAMAR_EXTRA_COMBAT_STRENGTH_IN_GOLDEN_AGE', 'Amount', 5),
	('SIXFIX_TRAIT_COMBAT_BONUS_WHEN_IN_GOLDEN_AGE','AbilityType', 'SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS')

	;
INSERT OR IGNORE INTO UnitAbilities (UnitAbilityType, Name, Description,Permanent) VALUES 
	('SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS', 'LOC_SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS', 'LOC_SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS', 1);
INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES 
	('SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS','SIXFIX_TAMAR_EXTRA_COMBAT_STRENGTH_IN_GOLDEN_AGE'); 
INSERT INTO Types (Type, Kind) VALUES
	('SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS','KIND_ABILITY');
INSERT INTO TypeTags (Type, Tag) VALUES
	('SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS', 'CLASS_RECON'),
	('SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS', 'CLASS_MELEE'),
	('SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS', 'CLASS_RANGED'),
	('SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS', 'CLASS_ANTI_CAVALRY'),
	('SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS', 'CLASS_LIGHT_CAVALRY'),
	('SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS', 'CLASS_HEAVY_CAVALRY'),
	('SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS', 'CLASS_SIEGE'),
	('SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS', 'CLASS_NAVAL_MELEE'),
	('SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS', 'CLASS_NAVAL_RANGED'),
	('SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS', 'CLASS_NAVAL_RAIDER'),
	('SIXFIX_ABILITY_TAMAR_GOLDEN_AGE_COMBAT_BONUS', 'CLASS_NAVAL_CARRIER')
	;
*/


INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
	('TRAIT_LEADER_RELIGION_CITY_STATES', 'SIXFIX_TAMAR_FAITH_PURCHASE_DISCOUNT_IN_GOLDEN_AGE')
	--THESE ARE BUGGED?  causes crashes when displaying combat diff against an enemy unit
	--('TRAIT_LEADER_RELIGION_CITY_STATES', 'SIXFIX_TAMAR_MORE_FAITH_ON_KILL_IN_GOLDEN_AGE')
	--('TRAIT_LEADER_RELIGION_CITY_STATES', 'SIXFIX_TRAIT_COMBAT_BONUS_WHEN_IN_GOLDEN_AGE')
	;

--INSERT INTO ModifierStrings (ModifierId, Context, Text) VALUES 
--	('SIXFIX_TAMAR_EXTRA_COMBAT_STRENGTH_IN_GOLDEN_AGE','Preview', '+5 [ICON_STRENGTH] when in a Golden Age');