-- kongo
-- Author: Cezas
-- DateCreated: 9/4/2021 7:35:33 PM
--------------------------------------------------------------
UPDATE Units SET Cost=80, Combat=35 WHERE UnitType='UNIT_KONGO_SHIELD_BEARER'; 
DELETE FROM ExcludedDistricts WHERE TraitType='TRAIT_LEADER_RELIGIOUS_CONVERT';
DELETE FROM TraitModifiers WHERE
	TraitType='TRAIT_CIVILIZATION_NKISI' AND ModifierId='TRAIT_DOUBLE_ARTIST_POINTS' OR 
	TraitType='TRAIT_CIVILIZATION_NKISI' AND ModifierId='TRAIT_DOUBLE_MUSICIAN_POINTS' 
;

/*
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES 
	('TRAIT_DISCOVER_ARTIFACTS_EARLY', )SET SubjectRequirementSetId='SIXFIX_PLAYER_HAS_HUMANISM_REQUIREMENTS' WHERE ModifierId='TRAIT_DISCOVER_ARTIFACTS_EARLY';
INSERT OR IGNORE INTO RequirementSets(RequirementSetId , RequirementSetType) VALUES
	('SIXFIX_PLAYER_HAS_HUMANISM_REQUIREMENTS' , 'REQUIREMENTSET_TEST_ALL');
INSERT OR IGNORE INTO RequirementSetRequirements(RequirementSetId , RequirementId) VALUES
	('SIXFIX_PLAYER_HAS_HUMANISM_REQUIREMENTS', 'SIXFIX_PLAYER_HAS_HUMANISM_REQUIREMENT');
INSERT OR IGNORE INTO Requirements(RequirementId , RequirementType) VALUES
	('SIXFIX_PLAYER_HAS_HUMANISM_REQUIREMENT' , 'REQUIREMENT_PLAYER_HAS_CIVIC');
INSERT OR IGNORE INTO RequirementArguments(RequirementId , Name, Value) VALUES
	('SIXFIX_PLAYER_HAS_HUMANISM_REQUIREMENT' , 'CivicType', 'CIVIC_HUMANISM');
*/

