-- poland
-- Author: Cezas
-- DateCreated: 10/10/2021 10:41:20 AM
--------------------------------------------------------------
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
	('SIXFIX_CULTURE_ON_RELIGIOUS_CONVERSION_BY_UNIT','MODIFIER_PLAYER_UNITS_ADJUST_INITIATION_YIELD_POPULATION')
	;

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('SIXFIX_CULTURE_ON_RELIGIOUS_CONVERSION_BY_UNIT','YieldType','YIELD_CULTURE'),
	('SIXFIX_CULTURE_ON_RELIGIOUS_CONVERSION_BY_UNIT','Amount',20)
	;

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
	('TRAIT_LEADER_LITHUANIAN_UNION', 'SIXFIX_CULTURE_ON_RELIGIOUS_CONVERSION_BY_UNIT');

UPDATE Units SET PrereqCivic='CIVIC_REFORMED_CHURCH' WHERE UnitType='UNIT_POLISH_HUSSAR';