-- poland
-- Author: Cezas
-- DateCreated: 10/10/2021 10:41:20 AM
--------------------------------------------------------------
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
	('SIXFIX_CULTURE_ON_RELIGIOUS_CONVERSION_BY_UNIT','MODIFIER_PLAYER_UNITS_ADJUST_INITIATION_YIELD_POPULATION')
	;
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('SIXFIX_CULTURE_ON_RELIGIOUS_CONVERSION_BY_UNIT','YieldType','YIELD_CULTURE'),
	('SIXFIX_CULTURE_ON_RELIGIOUS_CONVERSION_BY_UNIT','Amount',20)
	;
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
	('TRAIT_LEADER_LITHUANIAN_UNION', 'SIXFIX_CULTURE_ON_RELIGIOUS_CONVERSION_BY_UNIT');


--doesnt work on free cities
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent) VALUES
	('SIXFIX_TRAIT_RELIC_WHEN_CAPTURING_CITY','MODIFIER_PLAYER_CAPTURED_CITY_ATTACH_MODIFIER', 0, 0),
	('SIXFIX_GRANT_RELIC_ON_CAPTURE_MODIFIER','MODIFIER_PLAYER_GRANT_RELIC', 1, 1)
	;
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('SIXFIX_TRAIT_RELIC_WHEN_CAPTURING_CITY','ModifierId','SIXFIX_GRANT_RELIC_ON_CAPTURE_MODIFIER'),
	('SIXFIX_GRANT_RELIC_ON_CAPTURE_MODIFIER','Amount',1),
	('SIXFIX_GRANT_RELIC_ON_CAPTURE_MODIFIER','RelicSource','RELIC_SOURCE_TRIBAL_VILLAGE')
	;
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
	('TRAIT_CIVILIZATION_GOLDEN_LIBERTY', 'SIXFIX_TRAIT_RELIC_WHEN_CAPTURING_CITY');

UPDATE Units SET PrereqCivic='CIVIC_REFORMED_CHURCH' WHERE UnitType='UNIT_POLISH_HUSSAR';